# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Cache
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # Use Java 16
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16

      # Build the project
      - name: Build with Maven
        run: mvn -B clean package --file pom.xml

      # Upload the .jar file
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          path: target/*.jar
